name: Actualizador Automatico

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          pip install requests
          # Estas librerías son obligatorias para que Chromium funcione en Linux
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2
          npm install puppeteer

      - name: Run Python script
        run: python actualizar_lista.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Bot Mira TV"
          git config --global user.email "bot@mira-tv-gratis.com"
          git add canales.json lista.m3u || true
          git commit -m "Actualizacion automatica de enlaces" || echo "No hay cambios para commitear"
          git push
