name: Actualizador Automatico

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          sudo apt-get update
          # Instalamos Chrome estable y las dependencias gráficas necesarias
          sudo apt-get install -y google-chrome-stable libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2t64 libxss1
          npm install puppeteer axios

      - name: Run Update Script
        env:
          # Le decimos a Puppeteer que NO descargue su Chrome, que use el del sistema
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/google-chrome-stable'
        run: node actualizar_lista.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Bot Mira TV"
          git config --global user.email "bot@mira-tv-gratis.com"
          # Agregamos solo si existen
          git add canales.json || true
          git commit -m "Actualizacion automatica de enlaces (América TV)" || echo "No hay cambios para commitear"
          git push
