name: Test Manual

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Instalar dependencias base
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable libnss3 libnspr4 libatk1.0-0 libcups2 libdrm2 libgbm1 libasound2t64
      
      - name: Instalar librerías de Node
        run: |
          # Instalamos localmente en la carpeta del proyecto
          npm install puppeteer axios
      
      - name: Verificar instalación
        run: |
          # Esto nos dirá si la carpeta existe realmente
          ls -d node_modules/puppeteer || echo "¡La carpeta no existe!"
          
      - name: Prueba directa de Chrome
        run: |
          google-chrome-stable --version
          
      - name: Ejecutar solo el capturador
        # Añadimos la variable de entorno para forzar el uso del Chrome instalado
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/google-chrome-stable'
        run: node obt_token.js
