name: Test Manual

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Instalar dependencias base
        run: |
          sudo apt-get update
          # Añadimos todas las librerías faltantes para headless
          sudo apt-get install -y google-chrome-stable libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2t64 libxss1 libpango-1.0-0 libpangocairo-1.0-0 libxshmfence1
      
      - name: Instalar librerías de Node
        run: npm install puppeteer axios
      
      - name: Ejecutar capturador con modo de depuración
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/google-chrome-stable'
          # DEBUG nos mostrará en la consola todo lo que hace Puppeteer
          DEBUG: 'puppeteer:*' 
        run: node obt_token.js
